/** Trusted renderer; generated bytes only execute in a dedicated, disposable worker. */
export const PLAYER_CSP =
  "sandbox allow-scripts; default-src 'none'; script-src 'unsafe-inline'; worker-src blob:; style-src 'unsafe-inline'; connect-src 'none'; img-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'";
export function playerHtml(code: string) {
  const source = JSON.stringify(code).replaceAll('<', '\\u003c');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Forge game preview</title><style>body{margin:0;padding:16px;background:#101b25;color:#eef5dd;font:14px system-ui}button{background:#dafa77;color:#15200b;border:0;border-radius:6px;padding:12px;margin:8px 8px 8px 0;font:inherit;cursor:pointer}canvas{display:block;width:100%;max-width:560px;aspect-ratio:1;background:#101b25;outline-offset:2px}#hud{display:flex;gap:20px;margin:8px 0}p{color:#b7c7b8;line-height:1.4}</style><div id="hud"><span id="game-state">ready</span><span id="score">Score 0</span></div><button id="start">Start game</button><button id="pause" disabled>Pause</button><canvas width="560" height="560" tabindex="0" aria-label="Game board"></canvas><p id="instructions">Arrows / WASD to move. Space to act. Escape pauses.</p><script>
  const source=${source};
  const canvas=document.querySelector('canvas'), ctx=canvas.getContext('2d');
  const state=document.querySelector('#game-state'), score=document.querySelector('#score');
  const start=document.querySelector('#start'), pause=document.querySelector('#pause');
  let worker=null,timer=null,watchdog=null,keys=new Set(),paused=false;
  function stop(){clearInterval(timer);clearTimeout(watchdog);if(worker)worker.terminate();worker=null;keys.clear();pause.disabled=true;}
  function fail(){stop();state.textContent='unavailable';document.querySelector('#instructions').textContent='The game stopped responding. Restart to try again.';}
  function draw(frame){
    if(!watchdog||!frame||frame.type!=='frame'||!['playing','won','lost'].includes(frame.status)||!Number.isFinite(frame.score)||!Array.isArray(frame.rects)||frame.rects.length>512)return fail();
    if(frame.rects.some(r=>!r||![r.x,r.y,r.w,r.h].every(n=>Number.isFinite(n)&&n>=0&&n<=560)||!/^#[0-9a-f]{6}$/i.test(r.color)))return fail();
    clearTimeout(watchdog);canvas.dataset.frames=String(Number(canvas.dataset.frames||0)+1);ctx.fillStyle='#101b25';ctx.fillRect(0,0,560,560);
    frame.rects.forEach(r=>{ctx.fillStyle=r.color;ctx.fillRect(r.x,r.y,r.w,r.h)});
    state.textContent=paused&&frame.status==='playing'?'paused':frame.status;score.textContent='Score '+Math.trunc(frame.score);
    if(typeof frame.message==='string')document.querySelector('#instructions').textContent=frame.message.slice(0,300);
    if(frame.status!=='playing')stop();
  }
  function send(message){if(!worker)return;clearTimeout(watchdog);watchdog=setTimeout(fail,1500);worker.postMessage(message);}
  start.onclick=()=>{stop();paused=false;pause.textContent='Pause';pause.disabled=false;state.textContent='starting';canvas.dataset.frames='0';start.textContent='Restart';
    const url=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);
    worker.onmessage=e=>draw(e.data);worker.onerror=fail;send({type:'reset',seed:1});
    // Only one step in flight. The watchdog bounds hung generated code.
    timer=setInterval(()=>{if(!paused&&worker&&!watchdog)send({type:'step',dt:100,keys:[...keys]});},100);
    canvas.focus();
  };
  // Clear the timeout handle after an accepted frame, enabling the next step.
  const render=draw;draw=function(frame){render(frame);if(worker)watchdog=null;};
  function toggle(){if(!worker)return;paused=!paused;keys.clear();pause.textContent=paused?'Resume':'Pause';state.textContent=paused?'paused':'playing';canvas.focus();}
  pause.onpointerdown=e=>e.preventDefault();pause.onclick=toggle;
  canvas.onkeydown=e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d',' '].includes(e.key)){e.preventDefault();keys.add(e.key)}if(e.key==='Escape'&&!e.repeat)toggle()};
  canvas.onkeyup=e=>keys.delete(e.key);
  canvas.onblur=()=>{keys.clear();if(worker){paused=true;pause.textContent='Resume';state.textContent='paused';}};
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&worker){paused=true;keys.clear();state.textContent='paused';pause.textContent='Resume';}});
  window.addEventListener('pagehide',stop);
</script></html>`;
}
